import org.apache.hadoop.security.proto.RefreshAuthorizationPolicyProtocolProtos.RefreshAuthorizationPolicyProtocolService;
public class FunctionUse12171 {
public void funcUse() {
RefreshAuthorizationPolicyProtocolService refreshauthorizationpolicyprotocolservice = new RefreshAuthorizationPolicyProtocolService();
refreshauthorizationpolicyprotocolservice.newReflectiveService(null);
}
}